### ISSUE TITLE
fail to suppress the output

### ISSUE THREAD

**Issue by shipengcheng1230** [fredrikekre/Literate.jl#58]
Hello, I used to add `;` at the end line of a block of code to suppress the output. But I couldn't do it now:

![image](https://user-images.githubusercontent.com/11856151/56055389-5accf500-5d27-11e9-9e06-e8dba67df18e.png)

How may I suppress the output in current version? Thank you!

**Comment by fredrikekre** [comment]
I can't reproduce, `;` still supresses output for me. Can you give some more information? What does the full code-block look like? Julia version? Literate.jl version?

**Comment by shipengcheng1230** [comment]
Hi, I just check the generated `.md` by Literate.jl and the outcomes do get suppressed. But when I check the generated `.md` by `mkdocs`, those are not. Do you have any clues about this?

**Comment by shipengcheng1230** [comment]
I am using Julia 1.1, Literate 1.1, mkdocs 1.0.4, and reproduce the issue with the following minimum codes:
```
➜  mkdocstest tree
.
├── make.jl
├── mkdocs.yml
└── src
    └── without_output.jl
```

Inside `without_output.jl`
```julia
a = 1
b = 2
c = 3;
```
The `mkdocs.yml`:
```yml
theme:
  name: 'material'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

nav:
  - Page1: 'with_output.md'
  - Page2: 'without_output.md'
```
The `make.jl`:
```julia
# Workaround for JuliaLang/julia/pull/28625
if Base.HOME_PROJECT[] !== nothing
    Base.HOME_PROJECT[] = abspath(Base.HOME_PROJECT[])
end

using Documenter, DocumenterMarkdown
using Plots # to not capture precompilation output

ENV["GKSwstype"] = "100"

using Literate

Literate.markdown("src/with_output.jl", "src")
Literate.markdown("src/without_output.jl", "src")

makedocs(
    doctest=false,
    # modules = [A],
    format = Markdown(),
)

deploydocs(
  repo = "github.com/shipengcheng1230/A.jl.git",
  deps = Deps.pip("pymdown-extensions", "pygments", "mkdocs", "python-markdown-math", "mkdocs-material"),
  target = "site",
  make = () -> run(`mkdocs build`),
)
```

Then after run `julia make.jl`, the generated `without_output.md` by Literate.jl:
~~~text
```@meta
EditURL = "https://github.com/TRAVIS_REPO_SLUG/blob/master/"
```

```@example with_output
a = 1
b = 2
c = 3;
```

*This page was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*

~~~

The generated by `mkdocs` is:
~~~text



```julia
a = 1
b = 2
c = 3;
```


```
3
```


*This page was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*

~~~

So the output isn't suppressed here. Can it be something wrong the `mkdocs`? 

Thank you!
